### PR TITLE
OpenStack: retry device path

### LINKED ISSUE #264: trying to mount incorrect volume in OpenStack
We are sometimes seeing situation like this when using OpenStack

```
I1027 06:32:33.238927    5130 volumes.go:300] Listing Openstack disks in 44a6f8538efe47cd9b55182e0a94e478/zone-1
I1027 06:32:33.660679    5130 mounter.go:288] Trying to mount master volume: "1bc7494f-be09-443b-8713-c478f8f2c5ed"
W1027 06:32:33.952050    5130 mounter.go:293] Error attaching volume "1bc7494f-be09-443b-8713-c478f8f2c5ed": error attaching volume 1bc7494f-be09-443b-8713-c478f8f2c5ed to server 061822c7-0fcd-4e49-96f3-ee0a204a448c: Bad request with: [POST https://foobar.com/v2.1/servers/061822c7-0fcd-4e49-96f3-ee0a204a448c/os-volume_attachments], error message: {"badRequest": {"message": "Invalid volume: volume 1bc7494f-be09-443b-8713-c478f8f2c5ed already attached", "code": 400}}
I1027 06:32:33.952206    5130 mounter.go:302] Currently attached volumes: []
I1027 06:32:33.952256    5130 boot.go:49] waiting for volumes
```

```
% openstack volume list --project kaas-clusterpr-6aef63-k8s-local
+--------------------------------------+------------------------------------------+-----------+------+---------------------------------------------------------------+
| ID                                   | Name                                     | Status    | Size | Attached to                                                   |
+--------------------------------------+------------------------------------------+-----------+------+---------------------------------------------------------------+
| 1dc01e68-a4db-4a67-b00f-da9e26fbd7af | 1.etcd-events.clusterpr-6aef63.k8s.local | in-use    |    8 | Attached to 18e52d29-2771-404c-bf6a-37a94631e506 on /dev/vdc  |
| ec8f7fa7-2594-4619-88f5-83b5e93b2886 | 1.etcd-main.clusterpr-6aef63.k8s.local   | in-use    |    8 | Attached to 18e52d29-2771-404c-bf6a-37a94631e506 on /dev/vdd  |
| 854de0e0-39ba-43f3-982b-b1affc774e55 | 3.etcd-events.clusterpr-6aef63.k8s.local | in-use    |    8 | Attached to 061822c7-0fcd-4e49-96f3-ee0a204a448c on /dev/vdd  |
| 7e549e7b-7105-46c7-b976-2f3bb4bf6c8f | 2.etcd-events.clusterpr-6aef63.k8s.local | in-use    |    8 | Attached to 9d55ba26-ee07-4422-afa1-b37ffec92d73 on /dev/vdd  |
| 52d58cb5-71da-415f-8695-e9bea97380a6 | 3.etcd-main.clusterpr-6aef63.k8s.local   | in-use    |    8 | Attached to 9d55ba26-ee07-4422-afa1-b37ffec92d73 on /dev/vdc  |
| 1bc7494f-be09-443b-8713-c478f8f2c5ed | 2.etcd-main.clusterpr-6aef63.k8s.local   | available |    8 |                                                               |
+--------------------------------------+------------------------------------------+-----------+------+---------------------------------------------------------------+
```

So for some reason manager decides to take incorrect volume. Maybe better tags for volumes needed? I am running this in single zone so volumes can be mounted to any master.

edit:
Hmm now when I check the error message and volume list, the ids actually match to non-mounted volume but the volume is not somehow attached? but it says its attached?

### PR DESCRIPTION
**Pull request by zetaab**
fixes #264

### CODE REVIEW

**Comment by zetaab** [comment]
@justinsb what you think about this solution? At least we have sometimes quite high delay when we mount volumes in openstack. That leads to situations that I mentioned in issue. If we could calm down for a second and wait does the volume attach to machine and then continue.

I have not tested this yet

**Comment by zetaab** [comment]
it looks like working better now
```
I1027 19:26:16.981132    5075 main.go:254] Mounting available etcd volumes matching tags [KubernetesCluster=calc.k8s.local k8s.io/etcd/main k8s.io/role/master=1]; nameTag=k8s.io/etcd/main
I1027 19:26:16.981157    5075 volumes.go:301] Listing Openstack disks in 9ebaa4069d4d4e009a94e85a811ea8a1/zone-1
I1027 19:26:17.363638    5075 mounter.go:288] Trying to mount master volume: "c8503311-3f0b-4459-9bf8-5fb2241e40d4"
I1027 19:26:18.966990    5075 mounter.go:302] Currently attached volumes: [0xc000112f00]
I1027 19:26:18.967026    5075 mounter.go:64] Master volume "c8503311-3f0b-4459-9bf8-5fb2241e40d4" is attached at "/dev/vdd"
I1027 19:26:18.972477    5075 mounter.go:78] Doing safe-format-and-mount of /dev/vdd to /mnt/master-2.etcd-main.calc.k8s.local
I1027 19:26:18.972534    5075 volumes.go:368] open /rootfs/dev/disk/by-id/: no such file or directory... retrying
I1027 19:26:24.972769    5075 volumes.go:368] open /rootfs/dev/disk/by-id/: no such file or directory... retrying
I1027 19:26:30.972966    5075 volumes.go:368] open /rootfs/dev/disk/by-id/: no such file or directory... retrying
I1027 19:26:36.973235    5075 volumes.go:368] open /rootfs/dev/disk/by-id/: no such file or directory... retrying
I1027 19:26:42.974171    5075 volumes.go:368] open /rootfs/dev/disk/by-id/: no such file or directory... retrying
I1027 19:26:48.974414    5075 volumes.go:347] Found disk attached as "virtio-c8503311-3f0b-4459-9"; full devicepath: /rootfs/dev/disk/by-id/virtio-c8503311-3f0b-4459-9
I1027 19:26:48.974443    5075 mounter.go:116] Found volume "c8503311-3f0b-4459-9bf8-5fb2241e40d4" mounted at device "/dev/disk/by-id/virtio-c8503311-3f0b-4459-9"
```

**Comment by zetaab** [comment]
now this is much better

```
I1027 19:58:34.358625    4907 mounter.go:64] Master volume "788c4186-b3aa-45e9-9e6f-d1bddfc1e6fd" is attached at "/dev/vdd"
I1027 19:58:34.358661    4907 mounter.go:78] Doing safe-format-and-mount of /dev/vdd to /mnt/master-3.etcd-main.calc.k8s.local
I1027 19:58:34.358756    4907 volumes.go:368] Failed to find device for the volumeID: "788c4186-b3aa-45e9-9e6f-d1bddfc1e6fd"... retrying
I1027 19:58:40.359047    4907 volumes.go:368] Failed to find device for the volumeID: "788c4186-b3aa-45e9-9e6f-d1bddfc1e6fd"... retrying
I1027 19:58:46.359393    4907 volumes.go:368] Failed to find device for the volumeID: "788c4186-b3aa-45e9-9e6f-d1bddfc1e6fd"... retrying
I1027 19:58:52.359698    4907 volumes.go:347] Found disk attached as "virtio-788c4186-b3aa-45e9-9"; full devicepath: /rootfs/dev/disk/by-id/virtio-788c4186-b3aa-45e9-9
```

the longest time that I saw was 1.5minutes from attach call that the volume were in machine. That is why I wait 2.5minutes.

**Comment by zetaab** [comment]
@justinsb can you check this? Perhaps we could get this into kops 1.16 alpha 1?

**Comment by zetaab** [comment]
@justinsb ping, could you check this. We are seeing this problem quite often

File: pkg/volumes/openstack/volumes.go [hunk 1]
```diff
@@ -352,13 +354,58 @@ func GetDevicePath(volumeID string) (string, error) {
 	return "", fmt.Errorf("Failed to find device for the volumeID: %q", volumeID)
 }
 
+// probeVolume probes volume in compute
+// see issue https://github.com/kubernetes/cloud-provider-openstack/issues/705
+func probeVolume() error {
+	// rescan scsi bus
+	scsiPath := "/sys/class/scsi_host/"
+	if dirs, err := ioutil.ReadDir(scsiPath); err == nil {
```
Comment (justinsb) [inline pkg/volumes/openstack/volumes.go]: Some warning on errors from ReadDir or WriteFile would be good here, so that we know if we aren't able to trigger a probe (e.g. because we're in a container).  Maybe also a V(2).Infof for each /scan path we write, so that we affirmatively know it's working also (at v=2)

File: pkg/volumes/openstack/volumes.go [hunk 2]
```diff
@@ -352,13 +354,58 @@ func GetDevicePath(volumeID string) (string, error) {
...
+	}
+	return nil
+}
+
 // FindMountedVolume implements Volumes::FindMountedVolume
 func (_ *OpenstackVolumes) FindMountedVolume(volume *volumes.Volume) (string, error) {
-	device, err := GetDevicePath(volume.ProviderID)
-	if err != nil {
-		return "", err
+	// wait for 2.5min is the volume attached and path found
```
Comment (justinsb) [inline pkg/volumes/openstack/volumes.go]: It does look like FindMountedVolume is itself called from a fairly tight loop in safeFormatAndMount.  I think the actual delta here is adding the scsi path probing and udevadm call.  I do wonder if other platforms would also benefit from similar code as well (and the idea of the smarter backoff is a good one, because safeFormatAndMount just waits a second in between polls...)

Oh... which makes me wonder if the actual problem here is that FindMountedVolume should be returning `"", nil` when it doesn't find the volume, it looks like it was returning `"", fmt.Errorf(..)` ?

Anyway, I'm in favor of getting this code in and seeing if we can maybe promote some of this into FindMountedVolume / other clouds.

**Comment by justinsb** [comment]
It looks like I need to better document the expectations of FindMountedVolume (?), but these are good changes that might also be applicable to other clouds - thanks @zetaab
