### PR TITLE
Use next attachment point when device already in use

### LINKED ISSUE #217: 1 minute delay on Kubernetes masters rollout introduced by race condition in assignDevice
We're testing a new Kubernetes cluster on AWS built with `kops` `1.12`, running etcd 3 with the `etcd-manager`. Each master node runs two instances of `etcd-manager` (`main` and `events`):

```
NAMESPACE     NAME                                                     READY   STATUS 
kube-system   etcd-manager-events-ip-172-22-129-234.ec2.internal       1/1     Running
kube-system   etcd-manager-main-ip-172-22-129-234.ec2.internal         1/1     Running
```

While testing the rollout of master nodes, we've observed that due to how `assignDevice` works it returns - at first try - the same device on both instances, introducing a 1 minute delay in the master rollout. To explain it, see the following (redacted) logs.

**`etcd-manager-events` logs**:

```
I0611 09:35:18.441963    9418 main.go:228] Mounting available etcd volumes matching tags [k8s.io/etcd/events k8s.io/role/master=1 kubernetes.io/cluster/REDACTED=owned]; nameTag=k8s.io/etcd/events
I0611 09:35:18.444481    9418 volumes.go:85] AWS API Request: ec2/DescribeVolumes
I0611 09:35:18.628872    9418 mounter.go:288] Trying to mount master volume: "vol-0033a5507d5546fe4"
I0611 09:35:18.628998    9418 volumes.go:85] AWS API Request: ec2/AttachVolume
I0611 09:35:18.890734    9418 volumes.go:339] AttachVolume request returned {
  AttachTime: 2019-06-11 09:35:18.866 +0000 UTC,
  Device: "/dev/xvdu",
  InstanceId: "i-0abc13d47bb0d19cd",
  State: "attaching",
  VolumeId: "vol-0033a5507d5546fe4"
}
I0611 09:35:18.890895    9418 volumes.go:85] AWS API Request: ec2/DescribeVolumes
I0611 09:35:18.983082    9418 mounter.go:302] Currently attached volumes: [0xc000238100]
I0611 09:35:18.983115    9418 mounter.go:64] Master volume "vol-0033a5507d5546fe4" is attached at "/dev/xvdu"
```

**`etcd-manager-main` logs**:

```
I0611 09:35:18.601952    9498 main.go:228] Mounting available etcd volumes matching tags [k8s.io/etcd/main k8s.io/role/master=1 kubernetes.io/cluster/REDACTED=owned]; nameTag=k8s.io/etcd/main
I0611 09:35:18.607188    9498 volumes.go:85] AWS API Request: ec2/DescribeVolumes
I0611 09:35:18.828121    9498 mounter.go:288] Trying to mount master volume: "vol-045d841d4ec069864"
I0611 09:35:18.828251    9498 volumes.go:85] AWS API Request: ec2/AttachVolume
W0611 09:35:19.114926    9498 mounter.go:293] Error attaching volume "vol-045d841d4ec069864": Error attaching EBS volume "vol-045d841d4ec069864": InvalidParameterValue: Invalid value '/dev/xvdu' for unixDevice. Attachment point /dev/xvdu is already in use
        status code: 400, request id: b668745c-64b9-46a0-af1a-61c6352daaed
I0611 09:35:19.114951    9498 mounter.go:302] Currently attached volumes: []
I0611 09:35:19.114966    9498 boot.go:49] waiting for volumes
I0611 09:36:19.115312    9498 volumes.go:85] AWS API Request: ec2/DescribeVolumes
I0611 09:36:19.204717    9498 mounter.go:288] Trying to mount master volume: "vol-045d841d4ec069864"
I0611 09:36:19.204841    9498 volumes.go:85] AWS API Request: ec2/AttachVolume
I0611 09:36:19.483306    9498 volumes.go:339] AttachVolume request returned {
  AttachTime: 2019-06-11 09:36:19.439 +0000 UTC,
  Device: "/dev/xvdv",
  InstanceId: "i-0abc13d47bb0d19cd",
  State: "attaching",
  VolumeId: "vol-045d841d4ec069864"
}
I0611 09:36:19.483477    9498 volumes.go:85] AWS API Request: ec2/DescribeVolumes
I0611 09:36:19.614795    9498 mounter.go:302] Currently attached volumes: [0xc000096080]
I0611 09:36:19.614822    9498 mounter.go:64] Master volume "vol-045d841d4ec069864" is attached at "/dev/xvdv"
```

As you can see, since the first EBS volume attachment has failed due to `Attachment point /dev/xvdu is already in use` it will reconcile after 60 seconds, introducing a 60 seconds delay in the bootstrapping of master nodes.

**Few options / ideas to start the conversation**:
1. We do accept it and do nothing (should we document it, in this case?)
2. We introduce the support for `Volume.PreferredLocalDevice`, which is populated by an optional volume tag read from the cloud provider, so that `kops` can set a different preferred local device for each volume. The `Volume.PreferredLocalDevice` is then passed to `assignDevice()`, which will return the preferred one if set and available, otherwise will fallback to the current logic
3. We randomize the first device tried by `assignDevice()`, which will then iterate of the next ones starting from it (this just reduces the likelihood, at the cost of having `assignDevice()` behave in a non deterministic way)

### PR DESCRIPTION
**Pull request by hakman**
Trying to attach volumes with same device names adds unnecessary delays.
With this fix, kube-apiserver starts in less than a minute after NodeUp finishes.

Fixes #217

### CODE REVIEW

**Comment by hakman** [comment]
```
I0505 15:16:54.605527    8984 volumes.go:86] AWS API Request: ec2metadata/GetToken
I0505 15:16:54.606897    8984 volumes.go:86] AWS API Request: ec2metadata/GetDynamicData
I0505 15:16:54.608283    8984 volumes.go:86] AWS API Request: ec2metadata/GetMetadata
I0505 15:16:54.609035    8984 volumes.go:86] AWS API Request: ec2metadata/GetMetadata
I0505 15:16:54.609834    8984 volumes.go:86] AWS API Request: ec2metadata/GetMetadata
I0505 15:16:54.614547    8984 main.go:279] Mounting available etcd volumes matching tags [k8s.io/etcd/events k8s.io/role/master=1 kubernetes.io/cluster/k8s.test.com=owned]; nameTag=k8s.io/etcd/events
I0505 15:16:54.616581    8984 volumes.go:86] AWS API Request: ec2/DescribeVolumes
I0505 15:16:54.829148    8984 mounter.go:294] Trying to mount master volume: "vol-0c276c2e24d65df14"
I0505 15:16:54.829310    8984 volumes.go:86] AWS API Request: ec2/AttachVolume
W0505 15:16:55.102292    8984 volumes.go:341] Invalid value '/dev/xvdu' for unixDevice. Attachment point /dev/xvdu is already in use
I0505 15:16:55.102394    8984 volumes.go:86] AWS API Request: ec2/AttachVolume
I0505 15:16:55.412977    8984 volumes.go:347] AttachVolume request returned {
  AttachTime: 2020-05-05 15:16:55.384 +0000 UTC,
  Device: "/dev/xvdv",
  InstanceId: "i-08d1d1f8a9ebe3409",
  State: "attaching",
  VolumeId: "vol-0c276c2e24d65df14"
}
I0505 15:16:55.413125    8984 volumes.go:86] AWS API Request: ec2/DescribeVolumes
I0505 15:16:55.537078    8984 mounter.go:308] Currently attached volumes: [0xc0002b0000]
I0505 15:16:55.537099    8984 mounter.go:72] Master volume "vol-0c276c2e24d65df14" is attached at "/dev/xvdv"
```

**Comment by hakman** [comment]
CC @justinsb

File: pkg/volumes/aws/volumes.go [hunk 1]
```diff
@@ -320,24 +321,34 @@ func (a *AWSVolumes) AttachVolume(volume *volumes.Volume) error {
...
+				InstanceId: aws.String(a.instanceID),
+				VolumeId:   aws.String(volumeID),
+			}
 
-		klog.V(2).Infof("AttachVolume request returned %v", attachResponse)
+			attachResponse, err := a.ec2.AttachVolume(request)
+			if err != nil {
+				aerr, ok := err.(awserr.Error)
+				if ok && aerr.Code() == "InvalidParameterValue" {
+					klog.Warning(aerr.Message())
```
Comment (justinsb) [inline pkg/volumes/aws/volumes.go:343]: We probably should prefix this warning with some indication of what's going on (i.e. that this is "normal") - the raw AWS errors aren't always very intuitive.

File: pkg/volumes/aws/volumes.go [hunk 2]
```diff
@@ -320,24 +321,34 @@ func (a *AWSVolumes) AttachVolume(volume *volumes.Volume) error {
...
+					continue
```
Comment (justinsb) [inline pkg/volumes/aws/volumes.go:344]: Also a comment here that we are effectively leaving/leaking the value in the device-assignment map would be good, I think.

**Comment by justinsb** [comment]
Some nits for more verbose logging and comments, but this looks good - thank you!

/approve
/lgtm
